theme: jekyll-theme-minimal
title: BlackOS Info Page
timezone: Europe/london
logo: media/BliteLogo.png
description: BlackOS (C) is an ODH project which attempts to make the terminal more UI friendly. It introduces packages such as DisplayKernel and Trinkets, The former is an API for developing a Text based UI using the DisplayKernel Library, the latter is a feature rich C++ shell superposed onto the default shell. Both projects are open source and available via GPL v3.0.
future: true
