theme: jekyll-theme-minimal
logo: media/BliteLogo.png
title: Info Page for
description: BlackOS is an ODH project containing a series of terminal programs written in C++, which maintains the DisplayKernel library and the Trinkets Shell. Find out more about Operation Dark Horse (ODH) here: [in future]
